### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by RiotArchiveProject** [LoL-Fantome/LeagueDownloader#1]
I've never put in an issue on github before but regardless, issuing `leaguedownloader download -n lol_air_client -v 0.0.0.0 -o [dir]` will result in an unhandled exception on a file. I know there's a ton of 0kb files in the root directory of this specific patch so that might be related(?).
A similar result happens with `leaguedownloader download -n lol_game_client -v 0.0.0.0 -o [dir]` when it hit's the river textures.
Also a personal thank you for making this tool, the older tool I have was starting to fail on certain ranges so I'm glad this was made.

```
2478 files to download
Downloading file 0.0.0.0/LolClient.exe
Downloading file 0.0.0.0/LolClient.swf

Unhandled Exception: System.IO.InvalidDataException: Found invalid data while decoding.
   at System.IO.Compression.Inflater.DecodeDynamicBlockHeader()
   at System.IO.Compression.Inflater.Decode()
   at System.IO.Compression.Inflater.Inflate(Byte[] bytes, Int32 offset, Int32 length)
   at System.IO.Compression.DeflateStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)
   at LeagueDownloader.RADSInteractor.Inflate(Byte[] compressedData)
   at LeagueDownloader.RADSInteractor.DecompressZlib(Byte[] inputData)
   at LeagueDownloader.RADSInteractor.DownloadFiles(String directory, String projectName, String projectVersion, String filter, String filesRevision)
   at LeagueDownloader.Program.DownloadFiles(DownloadOptions opts)
   at LeagueDownloader.Program.<>c.<Main>b__6_3(DownloadOptions opts)
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 notParsedFunc)
   at LeagueDownloader.Program.Main(String[] args)

```

**Comment by ChewyBomber** [comment]
Thanks for the info, will check it out today.

**Comment by ChewyBomber** [comment]
@ProtoFgt Ok I investigated a bit, and it seems like some files from the early versions of RADS were not compressed correctly, which means that the issue you are facing isn't even an issue coming from my tool but actually from Riot 😃  Anyway, I'll release very soon a new version that handles this kind of behaviour so that these "broken" entries will simply be ignored. Thx for the help.

**Comment by RiotArchiveProject** [comment]
Thanks guys, appreciate it.
If I find any other issues with this release or the next one I'll let you know
