### ISSUE TITLE
Getting 403 after trying to get version 7.18

### ISSUE THREAD

**Issue by upDiogoSaraiva** [LoL-Fantome/LeagueDownloader#12]
```
.\LeagueDownloader.exe solution -n lol_game_client -o client [-v 1.0.4.0 -l en_gb]

Unhandled Exception: System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at LeagueDownloader.RADSInteractor.GetSolutionReleases(String solutionName)
   at LeagueDownloader.RADSInteractor.GetLatestSolutionRelease(String solutionName)
   at LeagueDownloader.RADSInteractor.InstallSolution(String directory, String solutionName, String solutionVersion, String localization, Nullable`1 deployMode)
   at LeagueDownloader.Program.InstallSolution(SolutionOptions opts)
   at LeagueDownloader.Program.<>c.<Main>b__8_0(SolutionOptions opts)
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,T5,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 parsedFunc5, Func`2 notParsedFunc)
   at LeagueDownloader.Program.Main(String[] args)
```

Is this project still alive? I have some .rofl files that i'm trying to see, and would need some previous versions to do so.

**Comment by lzardy** [comment]
Riot RADS CDN has been offline since May of 2021.
You will be unable to download any patch.

**Comment by upDiogoSaraiva** [comment]
Is there any other known way to view old .rofl files?

**Comment by lzardy** [comment]
You can decrypt and read the packets, but without the League client you cannot play them.

**Comment by ThexXTURBOXx** [comment]
Btw, if someone is still searching for the RADS, they have been archived:
Part 1: https://archive.org/details/league-of-legends-rads-patch-system-2010-2019
Part 2: https://archive.org/details/league-of-legends-rads-patch-system-2010-2019-part-2
Part 3: https://archive.org/details/league-of-legends-rads-patch-system-2010-2019-part-3
